// Character advance widths for DejaVu Sans, as fractions of the font size.
//
// MEASURED, not guessed: generated by scripts/calibrateFontMetrics.cjs, which
// renders each glyph repeatedly through resvg and derives the advance from the
// bounding box delta. Regenerate with:
//
//   node scripts/calibrateFontMetrics.cjs
//
// The card renderer uses these to wrap text. An eyeballed average (the previous
// approach) under-measured capitals and digits by ~20%, so headings and bullets
// full of dollar figures ran off the edge of the canvas.

const REGULAR = { "0": 0.64, "1": 0.64, "2": 0.64, "3": 0.64, "4": 0.64, "5": 0.64, "6": 0.64, "7": 0.64, "8": 0.64, "9": 0.64, " ": 0.32, "!": 0.4, "\"": 0.46, "#": 0.84, "$": 0.64, "%": 0.95, "&": 0.78, "'": 0.27, "(": 0.39, ")": 0.39, "*": 0.5, "+": 0.84, ",": 0.32, "-": 0.36, ".": 0.32, "/": 0.34, ":": 0.34, ";": 0.34, "<": 0.84, "=": 0.84, ">": 0.84, "?": 0.53, "@": 1, "A": 0.71, "B": 0.69, "C": 0.7, "D": 0.77, "E": 0.63, "F": 0.58, "G": 0.77, "H": 0.75, "I": 0.29, "J": 0.29, "K": 0.66, "L": 0.56, "M": 0.86, "N": 0.75, "O": 0.79, "P": 0.6, "Q": 0.79, "R": 0.69, "S": 0.63, "T": 0.59, "U": 0.73, "V": 0.68, "W": 0.99, "X": 0.69, "Y": 0.61, "Z": 0.69, "[": 0.39, "\\": 0.34, "]": 0.39, "^": 0.84, "_": 0.5, "`": 0.5, "a": 0.61, "b": 0.63, "c": 0.55, "d": 0.63, "e": 0.62, "f": 0.34, "g": 0.63, "h": 0.63, "i": 0.28, "j": 0.28, "k": 0.58, "l": 0.28, "m": 0.97, "n": 0.63, "o": 0.61, "p": 0.63, "q": 0.63, "r": 0.39, "s": 0.52, "t": 0.39, "u": 0.63, "v": 0.59, "w": 0.82, "x": 0.59, "y": 0.59, "z": 0.52, "{": 0.64, "|": 0.34, "}": 0.64, "~": 0.84, "•": 0.59, "–": 0.5, "—": 1, "€": 0.64, "£": 0.64, "₺": 0.64, "ı": 0.28, "ş": 0.52, "ğ": 0.63, "ç": 0.55, "ö": 0.61, "ü": 0.63, "İ": 0.29, "Ş": 0.63, "Ğ": 0.77, "Ç": 0.7, "Ö": 0.79, "Ü": 0.73, "é": 0.62, "á": 0.61 };

const BOLD = { "0": 0.7, "1": 0.7, "2": 0.7, "3": 0.7, "4": 0.7, "5": 0.7, "6": 0.7, "7": 0.7, "8": 0.7, "9": 0.7, " ": 0.35, "!": 0.46, "\"": 0.52, "#": 0.84, "$": 0.7, "%": 1, "&": 0.87, "'": 0.31, "(": 0.46, ")": 0.46, "*": 0.52, "+": 0.84, ",": 0.38, "-": 0.42, ".": 0.38, "/": 0.37, ":": 0.4, ";": 0.4, "<": 0.84, "=": 0.84, ">": 0.84, "?": 0.58, "@": 1, "A": 0.77, "B": 0.76, "C": 0.73, "D": 0.83, "E": 0.68, "F": 0.68, "G": 0.82, "H": 0.84, "I": 0.37, "J": 0.37, "K": 0.77, "L": 0.64, "M": 1, "N": 0.84, "O": 0.85, "P": 0.73, "Q": 0.85, "R": 0.77, "S": 0.68, "T": 0.71, "U": 0.81, "V": 0.77, "W": 1.1, "X": 0.77, "Y": 0.72, "Z": 0.73, "[": 0.46, "\\": 0.37, "]": 0.46, "^": 0.84, "_": 0.5, "`": 0.5, "a": 0.67, "b": 0.72, "c": 0.59, "d": 0.72, "e": 0.68, "f": 0.4, "g": 0.72, "h": 0.71, "i": 0.34, "j": 0.34, "k": 0.67, "l": 0.34, "m": 1.04, "n": 0.71, "o": 0.69, "p": 0.72, "q": 0.72, "r": 0.49, "s": 0.6, "t": 0.48, "u": 0.71, "v": 0.65, "w": 0.92, "x": 0.65, "y": 0.65, "z": 0.58, "{": 0.71, "|": 0.37, "}": 0.71, "~": 0.84, "•": 0.64, "–": 0.5, "—": 1, "€": 0.7, "£": 0.7, "₺": 0.7, "ı": 0.34, "ş": 0.6, "ğ": 0.72, "ç": 0.59, "ö": 0.69, "ü": 0.71, "İ": 0.37, "Ş": 0.68, "Ğ": 0.82, "Ç": 0.73, "Ö": 0.85, "Ü": 0.81, "é": 0.68, "á": 0.67 };

// Unknown glyphs fall back to a value slightly above the alphabet average, so
// an unmeasured character wraps early rather than overflowing.
const FALLBACK_REGULAR = 0.64;
const FALLBACK_BOLD = 0.70;

/** Width of `text` in user units at `fontSize`. */
export function measureText(text, fontSize, bold = false) {
  const table = bold ? BOLD : REGULAR;
  const fallback = bold ? FALLBACK_BOLD : FALLBACK_REGULAR;
  let em = 0;
  for (const ch of String(text)) em += table[ch] ?? fallback;
  return em * fontSize;
}

/** Largest font size (<= max) at which `text` fits within `maxWidth` on one line. */
export function fitFontSize(text, maxWidth, max, min = 14, bold = false) {
  for (let size = max; size > min; size -= 1) {
    if (measureText(text, size, bold) <= maxWidth) return size;
  }
  return min;
}

/** Greedy word wrap. Unbreakable words are hard-split so nothing escapes the canvas. */
export function wrapText(text, maxWidth, fontSize, bold = false) {
  const clean = String(text ?? '').trim();
  if (!clean) return [];
  const lines = [];
  let line = '';

  for (const word of clean.split(/\s+/)) {
    const candidate = line ? line + ' ' + word : word;
    if (measureText(candidate, fontSize, bold) <= maxWidth) { line = candidate; continue; }
    if (line) { lines.push(line); line = ''; }
    if (measureText(word, fontSize, bold) <= maxWidth) { line = word; continue; }
    let chunk = '';
    for (const ch of word) {
      if (measureText(chunk + ch, fontSize, bold) > maxWidth) { lines.push(chunk); chunk = ch; }
      else chunk += ch;
    }
    line = chunk;
  }
  if (line) lines.push(line);
  return lines;
}
